In [1]:
import numpy as np

In [4]:
#vector 0
vector = np.zeros(10)
vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#thay doi gia tri
vector[5] = 1
vector

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [9]:
#radom vector tu 10 den 50
vector = np.random.randint(10, 50, size=10)
vector

array([19, 16, 27, 42, 14, 18, 39, 32, 47, 29])

In [10]:
#dao vector
vector = [1, 2, 3, 4, 5, 6]
vector[::-1]

[6, 5, 4, 3, 2, 1]

In [13]:
#ma tran don vi
matran = np.identity(3)
matran

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
#ma tran 3x3 ramdom
matran = np.random.randint(1, 100, size=(3,3))
matran

array([[90, 63, 94],
       [50, 94, 84],
       [47,  2, 64]])

In [21]:
#tao ma tran 10x10 in max min
matran = np.random.randint(1, 100, size=(10, 10))
print(matran)
print(matran.min())
print(matran.max())

[[17 10 46 60  1 75 22  3 12 41]
 [36 31 79 49 53  1 78 81 84  4]
 [20 57 89 46 23 54 70 92 59 58]
 [26 81 71  8  6 83 62 59 67 48]
 [26 54 82 61 37 21 31 16 22 27]
 [66 36 36 79 14 96 77 31 66 44]
 [89 88 38 27 53 81 77 84 39  7]
 [44 82 36 44 40  9 66 25 75 51]
 [91  9 67  9 86 69 52 46 51 24]
 [57 54 48 44 47 52  8 83 48 67]]
1
96


In [24]:
#tao vector 30 radom 1 den 100 in tb
vector = np.random.randint(1, 100, size=30)
print(vector)
print(vector.mean())

[78 25 74 76 72  6 61 98 65 44 28 11 51 95 95 31 61 70 12 18 62 13 72  7
 10 71  2 59 23  6]
46.53333333333333


In [39]:
#tạo boder cho matran
matran = np.zeros((5,5))
matran1 = np.ones((np.shape(matran)[0] + 2, np.shape(matran)[1] + 2))
print(matran)
#print(matran1)
matran1[1:-1,1:-1] = matran
print(matran1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [41]:
#tạo boder cho matran
matran = np.random.randint(10,50, size=(6,7))
matran1 = np.zeros((np.shape(matran)[0] + 2, np.shape(matran)[1] + 2))
print(matran)
#print(matran1)
matran1[1:-1,1:-1] = matran
print(matran1)

[[16 28 49 46 23 11 10]
 [18 34 20 39 29 35 37]
 [46 36 48 38 10 29 38]
 [37 13 49 27 48 44 39]
 [19 32 41 37 12 31 11]
 [13 37 38 33 47 29 49]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 16. 28. 49. 46. 23. 11. 10.  0.]
 [ 0. 18. 34. 20. 39. 29. 35. 37.  0.]
 [ 0. 46. 36. 48. 38. 10. 29. 38.  0.]
 [ 0. 37. 13. 49. 27. 48. 44. 39.  0.]
 [ 0. 19. 32. 41. 37. 12. 31. 11.  0.]
 [ 0. 13. 37. 38. 33. 47. 29. 49.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [17]:
import numpy as np
matran = np.zeros((5,5))
n = len(matran[0])
for i in range(n-1):
    matran[i+1, i] = i+1
matran

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [71]:
vector = np.random.randint(1,10,10)
print(vector)
print(np.sort(vector))
print(-np.sort(-vector))

[2 6 3 7 5 7 1 1 8 7]
[1 1 2 3 5 6 7 7 7 8]
[8 7 7 7 6 5 3 2 1 1]


In [77]:
vector = np.random.random(10)
vector

array([0.78281119, 0.09753029, 0.28276271, 0.39771083, 0.61731034,
       0.0860587 , 0.91264728, 0.68054304, 0.94989107, 0.68037142])