# Kiểu dữ liệu

- Survived: Ordinal dữ liệu có thứ tự dạng 0-1
- Pclass: Ordinal dữ liệu có thứ tự cấp bậc trong xã hội
- Name: Nominal dữ liệu dạng chữ không có thứ tự
- Sex: Nominal dữ liệu dạng chữ không có thứ tự
- Age: continous nhận giá trị  liện trục trên miền giá trị(0-100)
- SibSp: Ordinal không có ý nghĩa toán học có thứ tự 0-1
- Ticket: Nominal dạng chữ không có thứ tự
- Fare: continous nhận giá trị liên tục
- Cabin: Nominal dữ liệu dạng chữ không có thứ tự
- Embarked: Nominal dữ liệu dạng chữ không có thứ tự

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('titanic.csv')

In [3]:
print(df.shape)
df.head(5)

(891, 12)


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
df.isnull().sum()


PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
X = df.values

In [8]:
from sklearn.impute import SimpleImputer
age = SimpleImputer(np.nan, strategy = 'mean')
X[:, 5] = age.fit_transform(X[:, 5].reshape(-1, 1)).ravel()
X

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

In [9]:
from sklearn.impute import SimpleImputer
cabin = SimpleImputer(np.nan, strategy = 'most_frequent')
X[:, 10] = cabin.fit_transform(X[:, 10].reshape(-1, 1)).ravel()
X

array([[1, 0, 3, ..., 7.25, 'B96 B98', 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, 'B96 B98', 'S'],
       ...,
       [889, 0, 3, ..., 23.45, 'B96 B98', 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, 'B96 B98', 'Q']], dtype=object)

In [11]:
from sklearn.impute import SimpleImputer
Embarked = SimpleImputer(np.nan, strategy = 'most_frequent') 
X[:, 11] = Embarked.fit_transform(X[:, 11].reshape(-1, 1)).ravel()
X

array([[1, 0, 3, ..., 7.25, 'B96 B98', 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, 'B96 B98', 'S'],
       ...,
       [889, 0, 3, ..., 23.45, 'B96 B98', 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, 'B96 B98', 'Q']], dtype=object)

In [12]:
df = pd.DataFrame.from_records(X, columns = df.columns)
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

# Chuẩn hoá dữ liệu

In [13]:
X

array([[1, 0, 3, ..., 7.25, 'B96 B98', 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, 'B96 B98', 'S'],
       ...,
       [889, 0, 3, ..., 23.45, 'B96 B98', 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, 'B96 B98', 'Q']], dtype=object)

In [14]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
fare_minmax_scaler = MinMaxScaler()
X[:, 9] = fare_minmax_scaler.fit_transform(X[:, 9].reshape(-1, 1)).ravel()
X

C:\Users\lexua\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[1, 0, 3, ..., 0.014151057562208049, 'B96 B98', 'S'],
       [2, 1, 1, ..., 0.13913573538264068, 'C85', 'C'],
       [3, 1, 3, ..., 0.015468569817999833, 'B96 B98', 'S'],
       ...,
       [889, 0, 3, ..., 0.04577135170121086, 'B96 B98', 'S'],
       [890, 1, 1, ..., 0.05855610025741262, 'C148', 'C'],
       [891, 0, 3, ..., 0.015126992566498259, 'B96 B98', 'Q']],
      dtype=object)

In [20]:
from sklearn.preprocessing import  LabelEncoder
sex_label_encoder = LabelEncoder()
X[:, 4] = sex_label_encoder.fit_transform(X[:, 4])
X

array([[1, 0, 3, ..., 0.014151057562208049, 'B96 B98', 'S'],
       [2, 1, 1, ..., 0.13913573538264068, 'C85', 'C'],
       [3, 1, 3, ..., 0.015468569817999833, 'B96 B98', 'S'],
       ...,
       [889, 0, 3, ..., 0.04577135170121086, 'B96 B98', 'S'],
       [890, 1, 1, ..., 0.05855610025741262, 'C148', 'C'],
       [891, 0, 3, ..., 0.015126992566498259, 'B96 B98', 'Q']],
      dtype=object)

In [16]:
age_minmax_scaler = MinMaxScaler()
X[:, 5] = age_minmax_scaler.fit_transform(X[:, 5].reshape(-1, 1)).ravel()
X

C:\Users\lexua\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[1, 0, 3, ..., 0.014151057562208049, 'B96 B98', 'S'],
       [2, 1, 1, ..., 0.13913573538264068, 'C85', 'C'],
       [3, 1, 3, ..., 0.015468569817999833, 'B96 B98', 'S'],
       ...,
       [889, 0, 3, ..., 0.04577135170121086, 'B96 B98', 'S'],
       [890, 1, 1, ..., 0.05855610025741262, 'C148', 'C'],
       [891, 0, 3, ..., 0.015126992566498259, 'B96 B98', 'Q']],
      dtype=object)

In [21]:
from sklearn.preprocessing import OneHotEncoder
embarked_onehot = OneHotEncoder()
embarked = embarked_onehot.fit_transform(X[:, 11].reshape(-1, 1)).toarray()
X = np.delete(X, 11, axis = 1)
X = np.concatenate((X, embarked), axis = 1)
X

array([[1, 0, 3, ..., 0.0, 0.0, 1.0],
       [2, 1, 1, ..., 1.0, 0.0, 0.0],
       [3, 1, 3, ..., 0.0, 0.0, 1.0],
       ...,
       [889, 0, 3, ..., 0.0, 0.0, 1.0],
       [890, 1, 1, ..., 1.0, 0.0, 0.0],
       [891, 0, 3, ..., 0.0, 1.0, 0.0]], dtype=object)

In [22]:
from sklearn.preprocessing import  LabelEncoder
name_label_encoder = LabelEncoder()
X[:, 3] = name_label_encoder.fit_transform(X[:, 3])
X

array([[1, 0, 3, ..., 0.0, 0.0, 1.0],
       [2, 1, 1, ..., 1.0, 0.0, 0.0],
       [3, 1, 3, ..., 0.0, 0.0, 1.0],
       ...,
       [889, 0, 3, ..., 0.0, 0.0, 1.0],
       [890, 1, 1, ..., 1.0, 0.0, 0.0],
       [891, 0, 3, ..., 0.0, 1.0, 0.0]], dtype=object)

In [23]:
from sklearn.preprocessing import  LabelEncoder
cabin_label_encoder = LabelEncoder()
X[:, 10] = cabin_label_encoder.fit_transform(X[:, 10])
X

array([[1, 0, 3, ..., 0.0, 0.0, 1.0],
       [2, 1, 1, ..., 1.0, 0.0, 0.0],
       [3, 1, 3, ..., 0.0, 0.0, 1.0],
       ...,
       [889, 0, 3, ..., 0.0, 0.0, 1.0],
       [890, 1, 1, ..., 1.0, 0.0, 0.0],
       [891, 0, 3, ..., 0.0, 1.0, 0.0]], dtype=object)

In [24]:
from sklearn.preprocessing import  LabelEncoder
ticket_label_encoder = LabelEncoder()
X[:, 8] = ticket_label_encoder.fit_transform(X[:, 8])
X

array([[1, 0, 3, ..., 0.0, 0.0, 1.0],
       [2, 1, 1, ..., 1.0, 0.0, 0.0],
       [3, 1, 3, ..., 0.0, 0.0, 1.0],
       ...,
       [889, 0, 3, ..., 0.0, 0.0, 1.0],
       [890, 1, 1, ..., 1.0, 0.0, 0.0],
       [891, 0, 3, ..., 0.0, 1.0, 0.0]], dtype=object)