# Kiểu dữ liệu

- age: Continous vì tuổi nhận giá trị liên tục trên miền giá trị (0-100)
- job: Nominal vì phân loại nghề nghiệp là dữ liệu dạng chữ không có thứ tự
- martital: Nominal vì dữ liệu dạng chữ không có thứ tự
- education: Ordinal vì dữ liệu dạng chữ có thứ tự
- balance: Continous vì giá trị liên tục, miền giá trị không xác định được
- housing: Ordinal vì dữ liệu dạng chữ, có thứ tự 0-1
- loan: Ordinal vì dữ liệu dạng chữ, có thứ tự 0-1
- contact: Nominal vì dữ liệu dạng chữ và không có thứ tự
- day: Ordinal vì dữ liệu dạng số không có ý nghĩa toán học có thứ tự từ 1-30
- month: Ordinal vì dữ liệu dang chữ có thứ tự 1-12

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("bank.csv", sep=';')

print(df.shape)
df.head(5)

(19, 10)


age          job  marital  education  balance housing loan   contact  day  \
0   30   unemployed  married    primary     1787      no   no  cellular   19   
1   33     services      NaN  secondary     4789     yes  yes  cellular   11   
2   35   management   single        NaN     1350     yes   no  cellular   16   
3   30   management  married   tertiary     1476     NaN  yes   unknown    3   
4   59  blue-collar  married  secondary        0     yes   no   unknown    5   

  month  
0   oct  
1   may  
2   apr  
3   jun  
4   may

In [4]:
df.isnull().sum()

age          0
job          1
marital      2
education    1
balance      0
housing      1
loan         0
contact      1
day          0
month        1
dtype: int64

# Missing Value

In [8]:
from sklearn.impute import SimpleImputer
X = df.values
job = SimpleImputer(np.nan, strategy = "most_frequent")
X[:, 1] = job.fit_transform(X[:, 1].reshape(-1, 1)).ravel()
X

array([[30, 'unemployed', 'married', 'primary', 1787, 'no', 'no',
        'cellular', 19, 'oct'],
       [33, 'services', nan, 'secondary', 4789, 'yes', 'yes', 'cellular',
        11, 'may'],
       [35, 'management', 'single', nan, 1350, 'yes', 'no', 'cellular',
        16, 'apr'],
       [30, 'management', 'married', 'tertiary', 1476, nan, 'yes',
        'unknown', 3, 'jun'],
       [59, 'blue-collar', 'married', 'secondary', 0, 'yes', 'no',
        'unknown', 5, 'may'],
       [35, 'management', 'single', 'tertiary', 747, 'no', 'no',
        'cellular', 23, 'feb'],
       [36, 'self-employed', 'married', 'tertiary', 307, 'yes', 'no',
        'cellular', 14, 'may'],
       [39, 'technician', 'married', 'secondary', 147, 'yes', 'no',
        'cellular', 6, 'may'],
       [41, 'entrepreneur', 'married', 'tertiary', 221, 'yes', 'no',
        'unknown', 14, 'may'],
       [43, 'services', 'married', 'primary', -88, 'yes', 'yes',
        'cellular', 17, 'apr'],
       [39, 'services', 'ma

In [9]:
from sklearn.impute import SimpleImputer
marital = SimpleImputer(np.nan, strategy = 'most_frequent')
X[:, 2] = marital.fit_transform(X[:, 2].reshape(-1, 1)).ravel()
X

array([[30, 'unemployed', 'married', 'primary', 1787, 'no', 'no',
        'cellular', 19, 'oct'],
       [33, 'services', 'married', 'secondary', 4789, 'yes', 'yes',
        'cellular', 11, 'may'],
       [35, 'management', 'single', nan, 1350, 'yes', 'no', 'cellular',
        16, 'apr'],
       [30, 'management', 'married', 'tertiary', 1476, nan, 'yes',
        'unknown', 3, 'jun'],
       [59, 'blue-collar', 'married', 'secondary', 0, 'yes', 'no',
        'unknown', 5, 'may'],
       [35, 'management', 'single', 'tertiary', 747, 'no', 'no',
        'cellular', 23, 'feb'],
       [36, 'self-employed', 'married', 'tertiary', 307, 'yes', 'no',
        'cellular', 14, 'may'],
       [39, 'technician', 'married', 'secondary', 147, 'yes', 'no',
        'cellular', 6, 'may'],
       [41, 'entrepreneur', 'married', 'tertiary', 221, 'yes', 'no',
        'unknown', 14, 'may'],
       [43, 'services', 'married', 'primary', -88, 'yes', 'yes',
        'cellular', 17, 'apr'],
       [39, 'services

In [10]:
from sklearn.impute import SimpleImputer
education = SimpleImputer(np.nan, strategy = 'most_frequent')
X[:, 3] = education.fit_transform(X[:, 3].reshape(-1, 1)).ravel()
X

array([[30, 'unemployed', 'married', 'primary', 1787, 'no', 'no',
        'cellular', 19, 'oct'],
       [33, 'services', 'married', 'secondary', 4789, 'yes', 'yes',
        'cellular', 11, 'may'],
       [35, 'management', 'single', 'secondary', 1350, 'yes', 'no',
        'cellular', 16, 'apr'],
       [30, 'management', 'married', 'tertiary', 1476, nan, 'yes',
        'unknown', 3, 'jun'],
       [59, 'blue-collar', 'married', 'secondary', 0, 'yes', 'no',
        'unknown', 5, 'may'],
       [35, 'management', 'single', 'tertiary', 747, 'no', 'no',
        'cellular', 23, 'feb'],
       [36, 'self-employed', 'married', 'tertiary', 307, 'yes', 'no',
        'cellular', 14, 'may'],
       [39, 'technician', 'married', 'secondary', 147, 'yes', 'no',
        'cellular', 6, 'may'],
       [41, 'entrepreneur', 'married', 'tertiary', 221, 'yes', 'no',
        'unknown', 14, 'may'],
       [43, 'services', 'married', 'primary', -88, 'yes', 'yes',
        'cellular', 17, 'apr'],
       [39, '

In [11]:
from sklearn.impute import SimpleImputer
housing = SimpleImputer(np.nan, strategy = 'most_frequent') #mode
X[:, 5] = housing.fit_transform(X[:, 5].reshape(-1, 1)).ravel()
X

array([[30, 'unemployed', 'married', 'primary', 1787, 'no', 'no',
        'cellular', 19, 'oct'],
       [33, 'services', 'married', 'secondary', 4789, 'yes', 'yes',
        'cellular', 11, 'may'],
       [35, 'management', 'single', 'secondary', 1350, 'yes', 'no',
        'cellular', 16, 'apr'],
       [30, 'management', 'married', 'tertiary', 1476, 'yes', 'yes',
        'unknown', 3, 'jun'],
       [59, 'blue-collar', 'married', 'secondary', 0, 'yes', 'no',
        'unknown', 5, 'may'],
       [35, 'management', 'single', 'tertiary', 747, 'no', 'no',
        'cellular', 23, 'feb'],
       [36, 'self-employed', 'married', 'tertiary', 307, 'yes', 'no',
        'cellular', 14, 'may'],
       [39, 'technician', 'married', 'secondary', 147, 'yes', 'no',
        'cellular', 6, 'may'],
       [41, 'entrepreneur', 'married', 'tertiary', 221, 'yes', 'no',
        'unknown', 14, 'may'],
       [43, 'services', 'married', 'primary', -88, 'yes', 'yes',
        'cellular', 17, 'apr'],
       [39,

In [13]:
from sklearn.impute import SimpleImputer
contact = SimpleImputer(np.nan, strategy = 'most_frequent') 
X[:, 7] = contact.fit_transform(X[:, 7].reshape(-1, 1)).ravel()
X

array([[30, 'unemployed', 'married', 'primary', 1787, 'no', 'no',
        'cellular', 19, 'oct'],
       [33, 'services', 'married', 'secondary', 4789, 'yes', 'yes',
        'cellular', 11, 'may'],
       [35, 'management', 'single', 'secondary', 1350, 'yes', 'no',
        'cellular', 16, 'apr'],
       [30, 'management', 'married', 'tertiary', 1476, 'yes', 'yes',
        'unknown', 3, 'jun'],
       [59, 'blue-collar', 'married', 'secondary', 0, 'yes', 'no',
        'unknown', 5, 'may'],
       [35, 'management', 'single', 'tertiary', 747, 'no', 'no',
        'cellular', 23, 'feb'],
       [36, 'self-employed', 'married', 'tertiary', 307, 'yes', 'no',
        'cellular', 14, 'may'],
       [39, 'technician', 'married', 'secondary', 147, 'yes', 'no',
        'cellular', 6, 'may'],
       [41, 'entrepreneur', 'married', 'tertiary', 221, 'yes', 'no',
        'unknown', 14, 'may'],
       [43, 'services', 'married', 'primary', -88, 'yes', 'yes',
        'cellular', 17, 'apr'],
       [39,

In [15]:
from sklearn.impute import SimpleImputer
month = SimpleImputer(np.nan, strategy = 'most_frequent')
X[:, -1] = month.fit_transform(X[:,-1].reshape(-1, 1)).ravel()
X

array([[30, 'unemployed', 'married', 'primary', 1787, 'no', 'no',
        'cellular', 19, 'oct'],
       [33, 'services', 'married', 'secondary', 4789, 'yes', 'yes',
        'cellular', 11, 'may'],
       [35, 'management', 'single', 'secondary', 1350, 'yes', 'no',
        'cellular', 16, 'apr'],
       [30, 'management', 'married', 'tertiary', 1476, 'yes', 'yes',
        'unknown', 3, 'jun'],
       [59, 'blue-collar', 'married', 'secondary', 0, 'yes', 'no',
        'unknown', 5, 'may'],
       [35, 'management', 'single', 'tertiary', 747, 'no', 'no',
        'cellular', 23, 'feb'],
       [36, 'self-employed', 'married', 'tertiary', 307, 'yes', 'no',
        'cellular', 14, 'may'],
       [39, 'technician', 'married', 'secondary', 147, 'yes', 'no',
        'cellular', 6, 'may'],
       [41, 'entrepreneur', 'married', 'tertiary', 221, 'yes', 'no',
        'unknown', 14, 'may'],
       [43, 'services', 'married', 'primary', -88, 'yes', 'yes',
        'cellular', 17, 'apr'],
       [39,

In [16]:
df = pd.DataFrame.from_records(X, columns = df.columns)
df.isnull().sum()

age          0
job          0
marital      0
education    0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
dtype: int64

# Chuan hoa du lieu

In [17]:
X

array([[30, 'unemployed', 'married', 'primary', 1787, 'no', 'no',
        'cellular', 19, 'oct'],
       [33, 'services', 'married', 'secondary', 4789, 'yes', 'yes',
        'cellular', 11, 'may'],
       [35, 'management', 'single', 'secondary', 1350, 'yes', 'no',
        'cellular', 16, 'apr'],
       [30, 'management', 'married', 'tertiary', 1476, 'yes', 'yes',
        'unknown', 3, 'jun'],
       [59, 'blue-collar', 'married', 'secondary', 0, 'yes', 'no',
        'unknown', 5, 'may'],
       [35, 'management', 'single', 'tertiary', 747, 'no', 'no',
        'cellular', 23, 'feb'],
       [36, 'self-employed', 'married', 'tertiary', 307, 'yes', 'no',
        'cellular', 14, 'may'],
       [39, 'technician', 'married', 'secondary', 147, 'yes', 'no',
        'cellular', 6, 'may'],
       [41, 'entrepreneur', 'married', 'tertiary', 221, 'yes', 'no',
        'unknown', 14, 'may'],
       [43, 'services', 'married', 'primary', -88, 'yes', 'yes',
        'cellular', 17, 'apr'],
       [39,

In [18]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import  LabelEncoder

In [24]:
age_minmax_scaler = MinMaxScaler()
X[:, 0] = age_minmax_scaler.fit_transform(X[:, 0].reshape(-1, 1)).ravel()
X

C:\Users\lexua\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.2564102564102564, 'unemployed', 'married', 'primary',
        0.20927566440854614, 0, 'no', 'cellular', 19, 'oct'],
       [0.33333333333333337, 'services', 'married', 'secondary',
        0.522146951537259, 1, 'yes', 'cellular', 11, 'may'],
       [0.3846153846153846, 'management', 'single', 'secondary',
        0.16373110995310058, 1, 'no', 'cellular', 16, 'apr'],
       [0.2564102564102564, 'management', 'married', 'tertiary',
        0.17686294945284003, 1, 'yes', 'unknown', 3, 'jun'],
       [1.0, 'blue-collar', 'married', 'secondary', 0.02303282959874935,
        1, 'no', 'unknown', 5, 'may'],
       [0.3846153846153846, 'management', 'single', 'tertiary',
        0.10088587806149035, 0, 'no', 'cellular', 23, 'feb'],
       [0.41025641025641024, 'self-employed', 'married', 'tertiary',
        0.05502866076081292, 1, 'no', 'cellular', 14, 'may'],
       [0.4871794871794872, 'technician', 'married', 'secondary',
        0.03835330901511204, 1, 'no', 'cellular', 6, 'may'],

In [21]:
balance_minmax_scaler = MinMaxScaler()
X[:, 4] = balance_minmax_scaler.fit_transform(X[:, 4].reshape(-1, 1)).ravel()
X

C:\Users\lexua\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.2564102564102564, 'unemployed', 'married', 'primary',
        0.20927566440854614, 'no', 'no', 'cellular', 19, 'oct'],
       [0.33333333333333337, 'services', 'married', 'secondary',
        0.522146951537259, 'yes', 'yes', 'cellular', 11, 'may'],
       [0.3846153846153846, 'management', 'single', 'secondary',
        0.16373110995310058, 'yes', 'no', 'cellular', 16, 'apr'],
       [0.2564102564102564, 'management', 'married', 'tertiary',
        0.17686294945284003, 'yes', 'yes', 'unknown', 3, 'jun'],
       [1.0, 'blue-collar', 'married', 'secondary', 0.02303282959874935,
        'yes', 'no', 'unknown', 5, 'may'],
       [0.3846153846153846, 'management', 'single', 'tertiary',
        0.10088587806149035, 'no', 'no', 'cellular', 23, 'feb'],
       [0.41025641025641024, 'self-employed', 'married', 'tertiary',
        0.05502866076081292, 'yes', 'no', 'cellular', 14, 'may'],
       [0.4871794871794872, 'technician', 'married', 'secondary',
        0.03835330901511204, 'yes'

In [22]:
housing_label_encoder = LabelEncoder()
X[:, 5] = housing_label_encoder.fit_transform(X[:, 5])
X

array([[0.2564102564102564, 'unemployed', 'married', 'primary',
        0.20927566440854614, 0, 'no', 'cellular', 19, 'oct'],
       [0.33333333333333337, 'services', 'married', 'secondary',
        0.522146951537259, 1, 'yes', 'cellular', 11, 'may'],
       [0.3846153846153846, 'management', 'single', 'secondary',
        0.16373110995310058, 1, 'no', 'cellular', 16, 'apr'],
       [0.2564102564102564, 'management', 'married', 'tertiary',
        0.17686294945284003, 1, 'yes', 'unknown', 3, 'jun'],
       [1.0, 'blue-collar', 'married', 'secondary', 0.02303282959874935,
        1, 'no', 'unknown', 5, 'may'],
       [0.3846153846153846, 'management', 'single', 'tertiary',
        0.10088587806149035, 0, 'no', 'cellular', 23, 'feb'],
       [0.41025641025641024, 'self-employed', 'married', 'tertiary',
        0.05502866076081292, 1, 'no', 'cellular', 14, 'may'],
       [0.4871794871794872, 'technician', 'married', 'secondary',
        0.03835330901511204, 1, 'no', 'cellular', 6, 'may'],

In [25]:
loan_label_encoder = LabelEncoder()
X[:, 6] = loan_label_encoder.fit_transform(X[:, 6])
X

array([[0.2564102564102564, 'unemployed', 'married', 'primary',
        0.20927566440854614, 0, 0, 'cellular', 19, 'oct'],
       [0.33333333333333337, 'services', 'married', 'secondary',
        0.522146951537259, 1, 1, 'cellular', 11, 'may'],
       [0.3846153846153846, 'management', 'single', 'secondary',
        0.16373110995310058, 1, 0, 'cellular', 16, 'apr'],
       [0.2564102564102564, 'management', 'married', 'tertiary',
        0.17686294945284003, 1, 1, 'unknown', 3, 'jun'],
       [1.0, 'blue-collar', 'married', 'secondary', 0.02303282959874935,
        1, 0, 'unknown', 5, 'may'],
       [0.3846153846153846, 'management', 'single', 'tertiary',
        0.10088587806149035, 0, 0, 'cellular', 23, 'feb'],
       [0.41025641025641024, 'self-employed', 'married', 'tertiary',
        0.05502866076081292, 1, 0, 'cellular', 14, 'may'],
       [0.4871794871794872, 'technician', 'married', 'secondary',
        0.03835330901511204, 1, 0, 'cellular', 6, 'may'],
       [0.538461538461538

In [26]:
marital_label_encoder = LabelEncoder()
X[:, 2] = marital_label_encoder.fit_transform(X[:, 2])
X

array([[0.2564102564102564, 'unemployed', 0, 'primary',
        0.20927566440854614, 0, 0, 'cellular', 19, 'oct'],
       [0.33333333333333337, 'services', 0, 'secondary',
        0.522146951537259, 1, 1, 'cellular', 11, 'may'],
       [0.3846153846153846, 'management', 1, 'secondary',
        0.16373110995310058, 1, 0, 'cellular', 16, 'apr'],
       [0.2564102564102564, 'management', 0, 'tertiary',
        0.17686294945284003, 1, 1, 'unknown', 3, 'jun'],
       [1.0, 'blue-collar', 0, 'secondary', 0.02303282959874935, 1, 0,
        'unknown', 5, 'may'],
       [0.3846153846153846, 'management', 1, 'tertiary',
        0.10088587806149035, 0, 0, 'cellular', 23, 'feb'],
       [0.41025641025641024, 'self-employed', 0, 'tertiary',
        0.05502866076081292, 1, 0, 'cellular', 14, 'may'],
       [0.4871794871794872, 'technician', 0, 'secondary',
        0.03835330901511204, 1, 0, 'cellular', 6, 'may'],
       [0.5384615384615385, 'entrepreneur', 0, 'tertiary',
        0.0460656591974987, 

In [27]:
from sklearn.preprocessing import OneHotEncoder

In [28]:
job_onehot = OneHotEncoder()
job = job_onehot.fit_transform(X[:, 1].reshape(-1, 1)).toarray()
X = np.delete(X, 1, axis = 1)
X = np.concatenate((X[:, 0:2], job, X[:, 2:]), axis = 1)
X

array([[0.2564102564102564, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 'primary', 0.20927566440854614, 0, 0, 'cellular', 19, 'oct'],
       [0.33333333333333337, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 'secondary', 0.522146951537259, 1, 1, 'cellular', 11, 'may'],
       [0.3846153846153846, 1, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 'secondary', 0.16373110995310058, 1, 0, 'cellular', 16,
        'apr'],
       [0.2564102564102564, 0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 'tertiary', 0.17686294945284003, 1, 1, 'unknown', 3, 'jun'],
       [1.0, 0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'secondary',
        0.02303282959874935, 1, 0, 'unknown', 5, 'may'],
       [0.3846153846153846, 1, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 'tertiary', 0.10088587806149035, 0, 0, 'cellular', 23,
        'feb'],
       [0.41025641025641024, 0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
        0.0, 'tertiary', 0.05502866076081292, 1,

In [29]:
education_onehot = OneHotEncoder()
education = education_onehot.fit_transform(X[:, 11].reshape(-1, 1)).toarray()
X = np.delete(X, 11, axis = 1)
X = np.concatenate((X[:, 0:11], job, X[:, 11:]), axis = 1)
X

array([[0.2564102564102564, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        0.20927566440854614, 0, 0, 'cellular', 19, 'oct'],
       [0.33333333333333337, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
        0.522146951537259, 1, 1, 'cellular', 11, 'may'],
       [0.3846153846153846, 1, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.16373110995310058, 1, 0, 'cellular', 16, 'apr'],
       [0.2564102564102564, 0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.17686294945284003, 1, 1, 'unknown', 3, 'jun'],
       [1.0, 0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.02303282959874935, 1, 0,
        'unknown', 5, 'may'],
       [0.3846153846153846, 1, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0

In [30]:
contact_label_encoder = LabelEncoder()
X[:, -3] = contact_label_encoder.fit_transform(X[:, -3])
X

array([[0.2564102564102564, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        0.20927566440854614, 0, 0, 0, 19, 'oct'],
       [0.33333333333333337, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
        0.522146951537259, 1, 1, 0, 11, 'may'],
       [0.3846153846153846, 1, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.16373110995310058, 1, 0, 0, 16, 'apr'],
       [0.2564102564102564, 0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.17686294945284003, 1, 1, 1, 3, 'jun'],
       [1.0, 0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.02303282959874935, 1, 0, 1,
        5, 'may'],
       [0.3846153846153846, 1, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,

In [31]:
month_label_encoder = LabelEncoder()
X[:, -1] = month_label_encoder.fit_transform(X[:, -1])
X

array([[0.2564102564102564, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        0.20927566440854614, 0, 0, 0, 19, 6],
       [0.33333333333333337, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
        0.522146951537259, 1, 1, 0, 11, 5],
       [0.3846153846153846, 1, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.16373110995310058, 1, 0, 0, 16, 0],
       [0.2564102564102564, 0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.17686294945284003, 1, 1, 1, 3, 4],
       [1.0, 0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.02303282959874935, 1, 0, 1,
        5, 5],
       [0.3846153846153846, 1, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.1008